# Generated by Django 3.1.7 on 2021-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_members'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='groups.Group'),
        ),
    ]
