# Generated by Django 3.1.7 on 2021-06-19 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
