# Generated by Django 3.1.7 on 2021-10-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_merge_20211019_1452'),
        ('faq', '0003_answer_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoted_answer', to='users.Account'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_answer', to='users.Account'),
        ),
    ]
