# Generated by Django 3.1.7 on 2022-01-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_merge_20211019_1452'),
        ('faq', '0004_auto_20211027_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reported_faqs', to='users.Account'),
        ),
    ]
