# Generated by Django 3.1.2 on 2021-01-12 11:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=users.models.profile_image_path),
        ),
    ]
