# Generated by Django 3.1.5 on 2021-01-22 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210122_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
