# Generated by Django 3.1.7 on 2021-05-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210517_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastjobs',
            name='description',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
