# Generated by Django 3.1.7 on 2021-05-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pastjobs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='This is my description', max_length=400),
        ),
    ]
