# Generated by Django 3.1.7 on 2021-05-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Graduation_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='start_year',
            field=models.IntegerField(default=2019),
        ),
    ]
