# Generated by Django 3.1.7 on 2021-05-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210531_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Graduation_year',
            new_name='graduation_year',
        ),
    ]
