# Generated by Django 3.1.7 on 2021-06-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210531_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pastjobs',
        ),
        migrations.AddField(
            model_name='pastjobs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.account'),
            preserve_default=False,
        ),
    ]
