# Generated by Django 3.1.7 on 2021-10-12 21:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210614_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_image_path),
        ),
    ]
