# Generated by Django 3.1.7 on 2021-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_account_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='signup_done',
            field=models.BooleanField(default=False),
        ),
    ]
