# Generated by Django 3.1.7 on 2021-10-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210717_1131'),
        ('users', '0015_auto_20211012_2118'),
    ]

    operations = [
    ]
