# Generated by Django 3.1.7 on 2022-01-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_merge_20211019_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('event_time', models.DateTimeField()),
                ('interested_users', models.ManyToManyField(blank=True, related_name='interested_events', to='users.Account')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_events', to='users.Account')),
            ],
        ),
    ]
