# Generated by Django 3.1.5 on 2021-01-22 12:24

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=post.models.EditorJsFieldMod(null=True),
        ),
    ]
