# Generated by Django 3.1.7 on 2021-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('post', '0002_auto_20210122_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='groups.Group'),
        ),
    ]
