# Generated by Django 3.1.7 on 2021-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_new',
            field=models.TextField(default='\\{\\}'),
        ),
    ]
