# Generated by Django 3.1.7 on 2021-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_content_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_new',
            field=models.JSONField(default=dict),
        ),
    ]
