# Generated by Django 3.1.7 on 2021-06-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210605_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_new',
            new_name='content',
        ),
    ]
