# Generated by Django 3.1.2 on 2021-01-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210112_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('group_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.TextField(null=True)),
                ('last_seen_msg', models.TextField(null=True)),
                ('members', models.ManyToManyField(related_name='chats', to='users.Account')),
            ],
        ),
    ]
