# Generated by Django 3.1.7 on 2021-04-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/groups'),
        ),
    ]
