# Generated by Django 3.1.7 on 2021-05-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210408_0955'),
        ('groups', '0002_auto_20210429_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='users.Account'),
        ),
    ]
